version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app2
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9001:9000"
    depends_on:
      - mysql

  web:
    image: nginx:alpine
    container_name: laravel_web2
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: laravel_db2
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: <your_root_password>
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
